server:
  port: 9999

spring:
  redis:
    database: 0
    host: node
    port: 16379
    password: Redis6379

test:
  person:
    lastName: hello
    age: 18
    boss: false
    birth: 2017/12/12
    maps: {k1: v1,k2: 12}
    lists:
      - lisi
      - zhaoliu
    dog:
      name: 小狗
      age: 12


#nacos:
#  config:
#    server-addr: node:8848
#  discovery:
#    server-addr: node:8848
